#!/bin/bash

PLUGIN_ID=$(xfconf-query -c xfce4-panel -lv | grep yup | awk '{print $1}' | tr -dc '0-9')

yay -Syu

echo ""
echo "===== Done - Press enter to exit ====="

read

xfce4-panel --plugin-event=genmon-$PLUGIN_ID:refresh:bool:true

exit 0

